blueprint:
  name: Presence Controlled Light
  description: Turn on and keep a light turned on, while presence is detected.
  domain: automation
  source_url: https://github.com/ChristianRiesen/homeassistant-blueprints/blob/main/presence_lights.yaml
  author: Christian Riesen
  input:
    occupancy_entities:
      name: Presence Sensors
      description: Select multiple occupancy sensors.
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
          multiple: true
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    turn_off_delay:
      name: Delay for turning off
      description: How long to wait after the occupancy is no longer detected, to turn off the light.
      default: 10
      selector:
        number:
          min: 0
          max: 86400
          unit_of_measurement: seconds

# Restart if during the delay the occupancy sensor detects someone again
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input occupancy_entities
  from: "off"
  to: "on"

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target: !input light_target
  - alias: "Wait until all occupancies are cleared"
    wait_for_trigger:
      - platform: state
        entity_id: !input occupancy_entities
        from: "on"
        to: "off"
  - alias: "Delay turning off"
    delay: !input turn_off_delay
  - alias: "Turn off the light"
    service: light.turn_off
    target: !input light_target